// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import Layout from './components/Layout';
import './globals.css';

export const metadata = {
  title: 'Swap Nova - Cross-Chain Token Swaps',
  description: 'Seamless cross-chain token swaps between Ethereum and Monad ecosystems. Gasless, secure, and instant atomic swaps with 1inch Fusion protocol.',
  keywords: [
    'cross-chain swap',
    'token swap',
    'ethereum',
    'monad',
    'arbitrum',
    'defi',
    'blockchain',
    'cryptocurrency',
    'atomic swap',
    'gasless',
    '1inch fusion',
    'web3',
    'decentralized exchange'
  ],
  authors: [{ name: 'Swap Nova Team' }],
  creator: 'Swap Nova',
  publisher: 'Swap Nova',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
